version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      -  ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

  postgresql_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - dbsellers-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sellers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123654
      


volumes:
  dbsellers-data:

networks:
  rabbitmq_go_net:
    driver: bridge